<style>
    .hand
    {
        cursor: pointer;
    }
</style>
<?php
if($this->lead)
{
    ?>
    <ul class="breadcrumb">
        <li>
            <a href="<?php echo $this->url("tb-admin");?>">
                Home
            </a> 
            <span class="divider"></span>
        </li>
        <li>
            <a href="<?php echo $this->url("tb-admin/lead");?>">
                Leads
            </a> 
            <span class="divider"></span>
        </li>
        <li class="active">#<?php echo $this->lead->getId();?></li>
    </ul>
    <div class="pull-left" style='width:30%'>
        <ul class="nav nav-tabs" id="myTab1" style="margin-bottom:10px">
            <li class="active"><a>Info</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="info">
                <div class="btn-group" title="Edit Lead" style="margin-bottom: 10px;">
                    <a class="btn btn-small addtooltip-right" title="Edit Lead" href="<?php echo $this->url("tb-admin/lead/edit", array("id" => $this->lead->getId()));?>">
                        <i class="icon-pencil"></i>
                    </a>
                </div>  
                <table class="table table-condensed">
                    <tr><th>Id</th><td><?php echo $this->lead->getId();?></td></tr>
                    <tr><th>Name</th><td><?php echo $this->lead->getName();?></td></tr>
                </table>
            </div>
        </div>
    </div>
    <div class="pull-right" style='width:65%;'>
        <ul class="nav nav-tabs" id="myTab" style="margin-bottom:10px">
            <li class="active"><a href="#contact_info">Contact Info</a></li>
            <li><a href="#contact_log">Contact Log</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="contact_info">
                <div>
                    <div class="btn-group">
                        <a class="btn btn-small" href="">
                            <i class="icon-phone"></i>
                            <i class="icon-plus icon-1x"></i>
                        </a>
                    </div>
                    <ul class="list-group">
                    <?php
                    if($this->lead->getPhoneNumbers()->count() >0)
                    {
                        foreach($this->lead->getPhoneNumbers() as $PhoneNumber)
                        {
                            ?><li class="list-group-item"><?php echo $PhoneNumber->toString();?></li><?php
                        }
                    }
                    else
                    {
                        ?><li class="list-group-item text-muted small">No Phone Numbers</li><?php
                    }
                    ?>
                    </ul>
                </div>
                <div>
                    <div class="btn-group">
                        <a class="btn btn-small" href="">
                            <i class="icon-envelope"></i>
                            <i class="icon-plus icon-1x"></i>
                        </a>
                    </div>
                    <ul class="list-group">
                    <?php
                    if($this->lead->getEmailAddresses()->count() >0)
                    {
                        foreach($this->lead->getEmailAddresses() as $EmailAddress)
                        {
                            ?><li class="list-group-item"><?php echo $EmailAddress->toString();?></li><?php
                        }
                    }
                    else
                    {
                        ?><li class="list-group-item text-muted small">No Email Addresses</li><?php
                    }
                    ?>
                    </ul>
                </div>
            </div>
            <div class="tab-pane" id="contact_log">
                <div>
                    <div class="btn-group">
                        <span>
                        <a class="btn btn-small" href="">
                            <i class="icon-phone"></i>
                            <i class="icon-plus icon-1x"></i>
                        </a>
                        </span>
                        <span class="text-muted"> / </span>
                        <span>
                        <a class="btn btn-small" href="">
                            <i class="icon-envelope"></i>
                            <i class="icon-plus icon-1x"></i>
                        </a>
                        </span>
                    </div>
                    <ul class="list-group">
                    <?php
                    if($this->lead->getContactLog()->getContacts()->count() > 0)
                    {
                        foreach($this->lead->getContactLog()->getContacts() as $Contact)
                        {
                            ?>
                            <li class="list-group-item">
                                <?php 
                                if($Contact->requiresAttention())
                                {
                                    ?><i class="icon-envelope"></i><?php
                                }
                                echo $Contact->getCreated()->format("m-d-y H:i");?>
                                    <i class="icon-eye-open contact_message_open text-primary hand"></i>
                                <div class="contact_message" style="display: none">
                                    <hr />
                                    <i class="icon-eye-close contact_message_close text-danger hand"></i>
                                    <br />
                                    <?php echo $Contact->getMessage();?>
                                </div>
                            </li>
                            <?php
                        }
                    }
                    else
                    {
                        ?><li class="text-muted small">No Contacts</li><?php
                    }
                    ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <?php
}
else echo "<div class='alert alert-block alert-error'>No lead with that id</div>";
?>
<div class="clearfix"></div>
<script>
    $('#myTab a').click(function (e) {
	e.preventDefault();
	$(this).tab('show');
    });
    
    $(".contact_message_open").click(function(){
        $(this).siblings(".contact_message").toggle();
    });
    
    $(".contact_message_close").click(function(){
        $(this).parent().toggle();
    });
</script>