
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>TB Admin</title>
    <meta name="robots" content="noindex,nofollow"/>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/font-awesome.min.css">

    <!-- jQuery Library -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <?php 
    echo $this->headLink();
    echo $this->headScript();
    ?>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="col-md-2" style="font-size: 32px;line-height: 42px;padding: 0;margin: 0;color: gray;">
            <img src="/img/turtle_logo.png" style="width:30px;padding: 0;margin: 0;vertical-align: top;"/> 
            TB Admin
        </div>
        <div class="col-md-7">
            <ul class="nav nav-tabs">
            <?php if($this->zfcUserIdentity() !== false)
            {
                $route_name = $this->ptgMatchedRoute();
                ?>
                <li class="<?php echo $route_name == "tb-admin" ? "active" : "";?>">
                    <a href="<?php echo $this->url("tb-admin");?>">Home</a>
                </li>
                <li class="<?php echo $route_name == "tb-admin/lead" ? "active" : "";?>">
                    <a href="<?php echo $this->url("tb-admin/lead");?>">Leads</a>
                </li>
                <li class="<?php echo $route_name == "tb-admin/user" ? "active" : "";?>">
                    <a href="<?php echo $this->url("tb-admin/user");?>">Users</a>
                </li>
                <li class="<?php echo $route_name == "tb-admin/category" ? "active" : "";?>">
                    <a href="<?php echo $this->url("tb-admin/category");?>">Categories</a>
                </li>
                <li class="<?php echo $route_name == "tb-admin/product" ? "active" : "";?>">
                    <a href="<?php echo $this->url("tb-admin/product");?>">Products</a>
                </li>
                <li class="<?php echo $route_name == "tb-admin/blog" ? "active" : "";?>">
                    <a href="<?php echo $this->url("tb-admin/blog");?>">Blog</a>
                </li>
                <?php
            }
            ?>
            </ul>
        </div>
        <div class="col-md-3">
            <?php if($this->zfcUserIdentity() !== false)
            {
                echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array("img_size" => 23 ), array("style" => "vertical-align:bottom")) 
                ?>
                <span style="font-size:16px;font-weight:600;"> 
                    Hello, 
                    <a href="<?php echo $this->url('tb-admin/user/mine') ?>">
                        <?php echo $this->zfcUserDisplayName() ?>
                    </a>
                    !
                </span>
                <a href="<?php echo $this->url('zfcuser/logout') ?>" style="vertical-align:top">
                    <i class="icon-signout"></i>
                </a>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <?php echo $this->flashMessenger()->render("success", array('alert', 'alert-success' , 'list-unstyled'));?>
        <?php echo $this->flashMessenger()->render("error", array('alert', 'alert-danger' , 'list-unstyled'));?>
    </div> <!-- /container -->
        <?php echo $this->content; ?>
</div> <!-- /container -->

<script>

    //Nav Bar Junk ----------
    var currentPath = window.location.pathname.replace(/^\/([^\/]*).*$/, '$1');
    currentPath = currentPath == '' ? 'home' : currentPath;
    document.getElementById('nav_' + currentPath + '_tab').className = 'active';
    //-----------------------
    //-----------------------

</script>
</body>
</html>
