
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>TB Admin</title>
    <meta name="robots" content="noindex,nofollow"/>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <!-- jQuery Library -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <!-- Custom styles for this template -->
    <link href="/css/justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="container">
    <div class="row">
        <div class="col-md-2" style="font-size: 32px;line-height: 42px;padding: 0;margin: 0;color: gray;">
            <img src="/img/turtle_logo.png" style="width:30px;padding: 0;margin: 0;vertical-align: top;"/> 
            TB Admin
        </div>
        <div class="col-md-10">
            <ul class="nav nav-tabs">
            <?php if($this->zfcUserIdentity() !== false)
            {
                ?>
                <li class="active"><a href="/tb-admin">Home</a></li>
                <li><a href="#">Leads</a></li>
                <li><a href="#">Users</a></li>
                <li><a href="/tb-admin/category">Categories</a></li>
                    <li>
                        <a href="<?php echo $this->url("zfcuser/logout");?>">
                            Logout 
                            <?php echo "(".$this->zfcUserIdentity()->getDisplayName().")";?>
                        </a>
                    </li>
                <?php
            }
            ?>
            </ul>
        </div>
    </div>
        <?php echo $this->content; ?>
</div> <!-- /container -->

<script>

    //Nav Bar Junk ----------
    var currentPath = window.location.pathname.replace(/^\/([^\/]*).*$/, '$1');
    currentPath = currentPath == '' ? 'home' : currentPath;
    document.getElementById('nav_' + currentPath + '_tab').className = 'active';
    //-----------------------
    //-----------------------

</script>
</body>
</html>
