<link href="/css/category.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<!-- Jumbotron -->
<div class="jumbotron">
    <h1><?php echo $this->category_title; ?></h1>
    <p class="lead"><?php echo $this->category_subdescription; ?></p>
    <p><a class="btn btn-lg btn-success" href="/get-started" role="button">Get started today</a></p>
</div>
<hr>

<div class="row">
    <div class="col-lg-12">
        <div class="list_carousel">
            <ul id="foo2">
                <?php

                /** @var \DirectoryIterator $pic */
                foreach(new DirectoryIterator( $this->category_image_directory ) as $pic)
                {

                    if($pic->isDot()
                        || $pic->isDir()
                        || $pic->getFilename() === 'index.php') continue;

                    echo '<li><div class="carou_tile" id="item"><img src="/img/'.$this->category_slug.'/' . $pic->getFilename() .'" />
                <div class="text"><h4>Horse Barn</h4><p>Starting at $11,000</p></div>
                </div></li>';
                }
                ?>
            </ul>
            <div class="clearfix"></div>
            <a id="prev2" class="prev" href="#"><i class="fa fa-arrow-circle-o-left" id="arrow_left"></i></a>
            <a id="next2" class="next" href="#"><i class="fa fa-arrow-circle-o-right" id="arrow_right"></i></a>
        </div>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-lg-12">
        <h1>Description</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <?php echo $this->description ;?>

        <h3>Features</h3>
        <ul>
            <?php
                foreach ($this->category_feature_bullet_points as $bullet_point_text){
                    echo '<li>' . $bullet_point_text . '</li>';
                }
            ?>
        </ul>
    </div>
    <div class="col-lg-6">
        <img src="<?php echo $this->category_main_pic_src ?>" class="round_corners" />
    </div>
</div>

<!--- JS Area Below ---->
<script type="text/javascript" language="javascript" src="/js/carouFredSel-6.2.1/jquery.carouFredSel-6.2.1-packed.js"></script>
<script type="text/javascript" language="javascript">

    $(function() {

        //	Scrolled by user interaction
        $('#foo2').carouFredSel({
            auto: false,
            prev: '#prev2',
            next: '#next2',
            pagination: "#pager2",
            mousewheel: true,
            swipe: {
                onMouse: true,
                onTouch: true
            }
        });

        $(".list_carousel li").hover(function(){
            $(this).find("div.text").slideDown("slow");
        },function(){
            $(this).find("div.text").slideUp("slow");
        });

    });

</script>