
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>Get in touch</h1>
    <p class="lead">Place an order, ask a question, or just chat - talk to us about anything!</p>
    <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>
</div>


<div class="row">
    <div class="col-lg-12">
        <div style="text-align: center;"><img src="/img/aframe.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:300px;" /></div>
        <h2 style="text-align: center;">Contact Information</h2>
        <p>We have our professional support and sales staff standing by. You can contact us via email or phone for any
        needs or special requests for service. Soon our updated contact information will be located here!</p>
    </div>

</div>