
<!-- Jumbotron -->
<div class="spacer"></div>
<div class="jumbotron realtree_light_background">
    <h1 class="white">Buildings</h1>
    <p class="white">Custom steel framed buildings built the way you need them built. </p>
    <p><a class="btn btn-lg btn-success" href="/get-started" role="button">Get started today</a></p>
</div>


<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div style="text-align: center;"><img class="img-responsive" src="/img/building.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:500px;height:323px;" /></div>
        <h2 style="text-align: center;">Buildings</h2>
        <p>Agricultural buildings, garden sheds, cottages, farm houses, dog sheds, chicken coops - we do it all. Need a
            specialized building? Contact us for an estimate on the building you need today!</p>
        <p><a class="btn btn-primary" href="/get-started" role="button">Get an Estimate &raquo;</a></p>
    </div>
</div>
