
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>Buildings</h1>
    <p class="lead">Custom steel framed buildings built the way you need them built. </p>
    <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>
</div>


<div class="row">
    <div class="col-lg-12">
        <div style="text-align: center;"><img src="/img/building.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:300px;height:194px;" /></div>
        <h2 style="text-align: center;">Buildings</h2>
        <p>Agricultural buildings, garden sheds, cottages, farm houses, dog sheds, chicken coops - we do it all. Need a
            specialized building? Contact us for an estimate on the building you need today!</p>
        <p><a class="btn btn-primary" href="#" role="button">Get an Estimate &raquo;</a></p>
    </div>
</div>