
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>Get Started!</h1>
    <p class="lead">We only need a few details to begin.</p>
</div>


<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <form role="form" method="post" action="/get-started/estimate">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Your email address">
            </div>

            <div class="form-group">
                <label for="exampleInputFile">Description</label>
                <textarea class="form-control" rows="3"></textarea>
                <p class="help-block">Tell us what you want.</p>
            </div>

            <button type="submit" class="btn btn-primary">Get your estimate!</button>
        </form>
    </div>
</div>