
<!-- Jumbotron -->
<div class="spacer"></div>
<div class="jumbotron realtree_light_background">
    <h1 class="text_shaddow">Get Started!</h1>
    <h2 class="text_shaddow bold">We only need a few details to begin.</h2>
</div>


<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <form role="form" method="post" action="/get-started/estimate">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" name="email" placeholder="Your email address">
            </div>
            <div class="form-group">
                <label for="exampleInputFile">Description</label>
                <textarea class="form-control" rows="3" name="description" id="description"></textarea>
                <p class="help-block">Tell us about the style and size of the building you want.</p>
            </div>

            <button type="submit" class="btn btn-primary">Get your estimate!</button>
        </form>
    </div>
</div>