
<!-- Jumbotron -->
<div class="spacer"></div>
<div class="jumbotron realtree_light_background">
    <h1 class="text_shaddow">Get Started!</h1>
    <h2 class="text_shaddow bold">We only need a few details to begin.</h2>
</div>

<?php echo $this->form()->openTag($this->form) ?>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="form-group">
            <?php 
            echo $this->flashMessenger()->render("get-started", array('alert', 'alert-danger' , 'list-unstyled'));
            echo $this->formLabel($this->form->get("emailaddress"));
            echo $this->formElementErrors(
                $this->form->get("emailaddress"), 
                array("class" => "alert alert-danger list-unstyled")
            );
            echo $this->formInput($this->form->get("emailaddress")
                ->setAttribute("class", "form-control"));?>
        </div>
        <div class="form-group">
            <?php 
            echo $this->formLabel($this->form->get("description"));
            echo $this->formElementErrors(
                $this->form->get("description"), 
                array("class" => "alert alert-danger list-unstyled")
            );
            echo $this->formTextArea($this->form->get("description")
                ->setAttribute("class", "form-control"));
            echo $this->formHidden($this->form->get("csrf"));
            ?>
        </div>
        <?php echo $this->formButton($this->form->get('submit')->setAttribute('class', 'btn btn-primary'));?>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>