<style>
    #index-content-cont
    {
        color: #FFF;
        font-family: Helvetica;
    }
    .index-content-main
    {
        text-align: center;
    }

    .index-content-main h2
    {
        font-size: 58px;
        font-weight: 600;
        line-height: 60px;
    }

    #index-content-row
    {
        margin-bottom: 25px;
    }

    #email-form
    {
        background-image: url('/img/email_form_bg.png');
        height:400px;
        width:975px;
    }

    #email-form-header
    {
        text-align: center;
        font-size: 28px;
        font-weight: 600;
        line-height: 80px;
    }

    #email-form-form
    {
        text-align: center;
    }

    #email-form-input
    {
        margin-top: 60px;
        height: 50px;
        font-size: 25px;
        width:480px;
    }

    #email-form-button
    {
        margin-top: 30px;
        height: 60px;
        font-size: 25px;
        width:500px;
    }

    #email-form-summary
    {
        font-size: 34px;
        line-height: 50px;
        font-style: italic;
    }
</style>
<script src="/PortableContractor/public/js/google_analytics.js"></script>
<div id="index-content-cont">
    <div class="row">
        <div class="span12 index-content-main">
            <h2>Thank you!</h2>
        </div>
    </div>
    <div class="row">
        <div class="span12 index-content-main">
            <h2 style="font-size:35px; margin-top: 45px;margin-bottom: 45px;">You'll be the first <br />to know when Portable Contractor<br/>goes live!</h2>
        </div>
    </div>
</div>