<?php
//change directory such that all paths are relative to the application root., /public
chdir(dirname(__DIR__));

//include the autoloader generated by composer
require('vendor/autoload.php');

//initialize the Application with Application config
$application = Zend\Mvc\Application::init(require 'config/application.config.php');

//run the application, responding to a type of Request with a type of Response
$application->run();