<link href="/css/category.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<!-- Jumbotron -->
<div class="spacer"></div>
<div class="jumbotron realtree_light_background">
    <h1><?php echo $this->name ?></h1>
    <p class="white"><?php echo $this->subdescription ?></p>
    <p>
        <form action="/get-started" method="post">
            <input type="hidden" name="interested_in" value="<?php echo $this->name ?>"/>
            <input type="submit" class="btn btn-lg btn-success" href="/get-started" role="button" value="Request Information">
        </form>
    </p>
</div>

<hr>

<div class="row">
    <div class="col-sm-12 col-lg-12">
        <h1>Description</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-6 col-lg-6">
        <p style="font-size:18px;"><?php echo $this->description?></p>

        <h3>Features</h3>
        <ul>

            <li class="slightly_larger">10 Year Warranty</li>
            <li class="slightly_larger">American Made</li>
            <li class="slightly_larger">Built to Last</li>
            <li class="slightly_larger">Made to fit your needs</li>
            <li class="slightly_larger">Guaranteed Lowest Price</li>

        </ul>
    </div>
    <div class="clearfix visible-sm"></div>
    <div class="col-sm-6 col-lg-6">
        <img src="/img/<?php echo $this->image_directory . "/" . $this->main_pic_src ?>" class="img-responsive" id="desc_main_pic" />
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <form action="/get-started" method="post">
            <input type="hidden" name="interested_in" value="<?php echo $this->name ?>"/>
            <p style="text-align: center;">
                <input type="submit" class="btn btn-lg btn-primary" role="button" value="Get Started Today &raquo;">
            </p>
        </form>
    </div>
</div>

