
<!-- Jumbotron -->
<div class="spacer"></div>
<div class="jumbotron realtree_light_background">
    <h1 class="text_shaddow">Carports built to suit</h1>
    <h2 class="text_shaddow bold">You need a special carport, we will build to your needs and specifications with extraordinary quality.</h2>
    <p><a class="btn btn-lg btn-success" href="/get-started" role="button">Get started today</a></p>
</div>


<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div style="text-align: center;"><img src="/img/aframe.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:500px;height:323px;" class="img-responsive"/></div>
        <h2 style="text-align: center;">Carports</h2>
        <p>We offer a wide range of carports and carport styles including portable carports, metal carports,
            carport kits and steel carports. Need a carport built to suit? 100% American made and supplied carports all
            come with a 10 year rust-through warranty. Countless options available, get started with an estimate below.</p>
        <p><a class="btn btn-primary" href="/get-started" role="button">Get an Estimate &raquo;</a></p>
    </div>
</div>
