
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>Garages &amp; Shops</h1>
    <p class="lead">We build them with the finest quality materials, to suit your special needs.</p>
    <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>
</div>


<div class="row">
    <div class="col-lg-12">
        <div style="text-align: center;"><img src="/img/shop.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:300px;height:194px;" /></div>
        <h2 style="text-align: center;" >Garages</h2>
        <p>We also specialize in enclosed buildings and shop style garages, built to last. All TurtleBuilt structures
            come with a 10 year rust-through warranty. Have a special need? Get started below for an estimate. </p>
        <p><a class="btn btn-primary" href="#" role="button">Get an Estimate &raquo;</a></p>
    </div>
</div>