<?php
/* @var $paginator \Zend\Paginator\Paginator */
$paginator = $this->paginator;
?>


<div class="list-group">

    <?php foreach($paginator as $post) : ?>

    <a href=blog/<?=$post->getSlug()?> class="list-group-item">
        <h2 class="list-group-item-heading"><?=$post->getTitle()?></h2>
        <p class="list-group-item-text"><?=$post->getExcerpt()?></p>
    </a>

    <?php endforeach; ?>

</div>