
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>TurtleBuilt Structures</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="container">
    <div class="masthead">
        <h3 class="text-muted">TurtleBuilt Structures</h3>
        <ul class="nav nav-justified">
            <li id="nav_home_tab"><a href="/">Home</a></li>
            <li id="nav_carports_tab"><a href="/carports">Carports</a></li>
            <li id="nav_garages_tab"><a href="/garages">Garages</a></li>
            <li id="nav_buildings_tab"><a href="/buildings">Buildings</a></li>
            <li id="nav_affiliate_tab"><a href="/affiliate">Affiliate</a></li>
            <li id="nav_contact_tab"><a href="/contact">Contact</a></li>
        </ul>
    </div>
<?php echo $this->content; ?>

    <!-- Site footer -->
    <div class="footer">
        <p>&copy; Polytechnic Group of Dallas &hearts; 2013</p>
    </div>

</div> <!-- /container -->

<script>
    var currentPath = window.location.pathname.replace(/^\/([^\/]*).*$/, '$1');
    currentPath = currentPath == '' ? 'home' : currentPath;
    document.getElementById('nav_' + currentPath + '_tab').className = 'active';
</script>
</body>
</html>
