
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="TurtleBuilt Carports, Buildings, and Garages are the finest quality American made structures. We build to suit your needs. Let us help you get started today!">
    <meta name="KEYWORDS" content="10 x 20 carport,2 car carport,aluminum awnings,aluminum carport,aluminum carports,
        aluminum patio cover,aluminum patio covers,american carport,american carports,american carports inc,american steel carport,
        american steel carports,american steel carports inc,attached carport,attached carports,awnings,barns,build a carport,
        build carport,building a carport,california carports,canopies,canopy,canopy carports,canvas carport,canvas carports,
        car canopies,car canopy,car carport,car port,car ports,quality carport,quality carports,quality carports com,
        quality carports inc,carport,quality,turtle,turtle carports, turtle carport,turtle built, turtle build, turtle structures,
        turtle built structures,carport addition,carport auto sales,carport awning,carport awnings,carport builders,
        carport building,carport building plans,carport canopies,carport canopy,carport com,carport construction,carport conversion,
        carport cost,carport cover,carport covers,carport dealers,carport design,carport designs,carport dimensions,carport enclosure,
        carport for sale,carport frame,carport garage,carport houston,carport ideas,carport inc,carport installation,carport kits,
        carport manufacturers,carport of tampa,carport parking,carport parts,carport pictures,carport plan,carport plans,
        carport prices,carport repair,carport roof,carport sales,carport shed,carport shelter,carport storage,carport structures,
        carport tarp,carport tent,carport tents,carport texas,carport to garage,carport with storage,carports,carports and canopies,
        carports and garages,carports com,carports dallas,carports florida,carports for sale,carports garages,carports houston,
        carports inc,carports kits,carports nc,carports oklahoma,carports texas,cheap carports,coast to coast carport,
        coast to coast carports,coast to coast carports inc,convert carport to garage,covered carport,covered parking,
        custom carports,deck,decks,detached carportdiy carport,do it yourself carport,door canopies,double carport,eagle carport,
        eagle carports,eagle carports inc,enclose a carport,enclose carport,enclosed carport,enclosed carports,enclosing a carport,
        enclosing carport,enclosures,free carport plans,free standing carport,free standing carports,free standing carport,
        garage,garage builders,garages gazebo,show to build a carport,kelty carport,kelty carport deluxe,lean to carport,
        metal carport,metal carport kits,metal carports,metal carports for sale,metal carports kits,metal garages,
        mobile home carport,mobile home carports,national carport,outdoor canopies,panther creek carport,panther creek carports,
        patio,patio canopies,patio canopy,patio cover,patio covers,patio enclosure,patio enclosures,patios,portable carport,
        portable carports,portable garage,prefab carport,prefab carports,room additions,rv carport,rv carports,rv covers,
        screen enclosures,screen rooms,shade structures,shed,sheds,shelters,solar carport,steel building,steel buildings,
        steel carport,steel carports,steel garage,steel garages,steel sheds,storage buildings,storage shed,storage sheds,
        sunrooms,superior carports,temporary carport,tnt carport,tnt carports,tnt carports inc,tri state carports,
        tri state carports inc,tri state carports,versatube carport,versatube carports,vinyl carport,wood carport,
        wood carports,wooden carport,wooden carports,addison,dallas,dfw,dfw carport,dfw carports, dallas carports,
        rockwall carport,rockwall carports,forney carports,forney,forney carport,mansfield,mansfield carports,texas,
        louisiana,oklahoma">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>TurtleBuilt</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
<!--    <link href="/css/bootstrap-responsive.css" rel="stylesheet">-->
    <!-- jQuery Library -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

    <![endif]-->
</head>
<style>
    body {
        background-image:url('../img/sheet-metal.png');
        background-repeat:repeat;
        background-size:32px 32px;
    }
</style>

<body>

<div class="container">

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><img src="/img/turtle_logo.png" style="height:32px;padding-right:5px;"/> turtle built</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li id="nav_home_tab"><a href="/">Home</a></li>
                    <li id="nav_carports_tab"><a href="/carports">Carports</a></li>
                    <li id="nav_garages_tab"><a href="/garages">Garages</a></li>
                    <li id="nav_buildings_tab"><a href="/buildings">Buildings</a></li>
                    <li id="nav_affiliate_tab"><a href="/affiliate">Affiliate</a></li>
                    <li id="nav_contact_tab"><a href="/contact">Contact</a></li>
                    <li id="nav_blog_tab"><a href="/blog">Blog</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    <div class="spacer"></div>
<?php echo $this->content; ?>

    <!-- Site footer -->
    <div class="footer realtree_light_background">
        <span class="footer_text">&copy; Polytechnic Group of Dallas &hearts; <?php echo date("Y"); ?></span>
    </div>

</div> <!-- /container -->
<script src="/js/bootstrap.min.js"></script>
<script>

    //Google Junk -----------
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44924640-2', 'turtlebuilt.com');
    ga('send', 'pageview');
    //-----------------------

</script>
</body>
</html>
