<?php
if($this->user)
{
    ?>
    <div class="pull-left" style='width:30%'>
        <ul class="nav nav-tabs" id="myTab1" style="margin-bottom:10px">
            <li class="active"><a>Info</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="info">
                <div class="btn-group" title="Edit User" style="margin-bottom: 10px;">
                    <a class="btn btn-small addtooltip-right" title="Edit User" href="<?php echo $this->url("tb-admin/user/edit", array("id" => $this->user->getId()));?>">
                        <i class="icon-pencil"></i>
                    </a>
<!--                    <a class="btn btn-small addtooltip-right" title="Change Password" href="<?php echo $this->url("zfcuser/changepassword", array("id" => $this->user->getId()));?>">
                        <i class="icon-asterisk"></i>
                    </a>-->
                </div>  
                <table class="table table-condensed">
                    <tr><th>Id</th><td><?php echo $this->user->getId();?></td></tr>
                    <tr><th>User Name</th><td><?php echo $this->user->getUsername();?></td></tr>
                    <tr><th>Email</th><td><?php echo $this->user->getEmail();?></td></tr>
                    <tr><th>Display Name</th><td><?php echo $this->user->getDisplayName();?></td></tr>
                    <tr><th>State</th><td><?php echo $this->user->getState();?></td></tr>
                </table>
            </div>
        </div>
    </div>
    <div class="pull-right" style='width:65%;'>
        <ul class="nav nav-tabs" id="myTab" style="margin-bottom:10px">
            <li class="active"><a href="#submittals">N/A</a></li>
            <!--<li><a href="#notes">Notes</a></li>-->
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="submittals">

            <!--<div class="tab-pane" id="notes">Notes</div>-->
            </div>
        </div>
    </div>
    <?php
}
else echo "<div class='alert alert-block alert-error'>No user with that id</div>";
?>
<div class="clearfix"></div>