
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>Make money from home!</h1>
    <p class="lead">Participate in the affiliate program that everyone has been talking about.</p>
</div>


<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div style="text-align: center;"><img src="/img/aframe.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:500px;height:323px;" class="img-responsive" /></div>
        <h2 style="text-align: center;">Affiliate Program Registration</h2>
        <p>Register here to establish yourself in the TurtleBuilt affiliate program. Soon you will be able to find more
            information on the affiliate program here on this page.</p>
        <!-- Begin MailChimp Signup Form -->
        <link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
        <style type="text/css">
            #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
            /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
               We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
        </style>
        <div id="mc_embed_signup">
            <form action="http://turtlebuilt.us7.list-manage.com/subscribe/post?u=c315ff62b9b2c3d0360982170&amp;id=8770e76834"
                  method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
                <div class="mc-field-group">
                    <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
                    </label>
                    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
                </div>
                <div class="mc-field-group">
                    <label for="mce-FNAME">First Name </label>
                    <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
                </div>
                <div class="mc-field-group">
                    <label for="mce-LNAME">Last Name </label>
                    <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
                </div>
                <div id="mce-responses" class="clear">
                    <div class="response" id="mce-error-response" style="display:none"></div>
                    <div class="response" id="mce-success-response" style="display:none"></div>
                </div>	<input type="submit" class="btn btn-primary" value="Register Now" name="subscribe" id="mc-embedded-subscribe" class="button">
            </form>
        </div>

        <!--End mc_embed_signup-->

    </div>
</div>
