
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>Make money from home!</h1>
    <p class="lead">Participate in the affiliate program that everyone has been talking about.</p>
    <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>
</div>


<div class="row">
    <div class="col-lg-12">
        <div style="text-align: center;"><img src="/img/aframe.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:300px;" /></div>
        <h2 style="text-align: center;">Affiliate</h2>
        <p>Register here to establish yourself in the TurtleBuilt affiliate program. Soon you will be able to find more
            information on the affiliate program here on this page.</p>
        <p><a class="btn btn-primary" href="#" role="button">Register Now &raquo;</a></p>
    </div>
</div>