<style>
    #index-content-cont
    {        
        color: #FFF;
        font-family: Helvetica;
    }
    .index-content-main
    {
        text-align: center;
    }
    
    .index-content-main h2
    { 
        font-size: 58px;
        font-weight: 600;
        line-height: 60px;
    }
    
    #index-content-row
    {
        margin-bottom: 25px;
    }
    
    #email-form
    {
        background-image: url('/img/email_form_bg.png');
        height:400px;
        width:975px;
    }
    
    #email-form-header
    {
        text-align: center;
        font-size: 28px;
        font-weight: 600;
        line-height: 80px;
    }
    
    #email-form-form
    {
        text-align: center;
    }
    
    #email-form-input
    {
        margin-top: 60px;
        height: 50px;
        font-size: 25px;
        width:480px;
    }
    
    #email-form-button
    {
        margin-top: 30px;
        height: 60px;
        font-size: 25px;
        width:500px;        
    }
    
    #email-form-summary
    {
        font-size: 34px;
        line-height: 50px;
        font-style: italic;
    }
</style>
<div id="index-content-cont">
</div>
