<style>
    #index-content-cont
    {        
        color: #FFF;
        font-family: Helvetica, sans-serif;
    }
    .index-content-main
    {
        text-align: center;
    }
    
    .index-content-main h2
    { 
        font-size: 58px;
        font-weight: 600;
        line-height: 60px;
    }
    
    #index-content-row
    {
        margin-bottom: 25px;
    }
    
    #email-form
    {
        background-image: url('/img/email_form_bg.png');
        height:400px;
        width:975px;
    }
    
    #email-form-header
    {
        text-align: center;
        font-size: 28px;
        font-weight: 600;
        line-height: 80px;
    }
    
    #email-form-form
    {
        text-align: center;
    }
    
    #email-form-input
    {
        margin-top: 60px;
        height: 50px;
        font-size: 25px;
        width:480px;
    }
    
    #email-form-button
    {
        margin-top: 30px;
        height: 60px;
        font-size: 25px;
        width:500px;        
    }
    
    #email-form-summary
    {
        font-size: 34px;
        line-height: 50px;
        font-style: italic;
    }
</style>
<div id="index-content-cont">
    <div class="row">
        <div class="span12 index-content-main">
            <h2>Easy Lead<br /> Management</h2>
        </div>
    </div>
    <div class="row">
        <div class="span4">
            <div class="index-content-point">
                <h3>Organize Your Business</h3>
                Let our easy-to-use Lead Management Software help organize your 
                business by efficiently and effectively storing your leads. 
            </div>
        </div>
        <div class="span4 index-content-point">
            <div class="index-content-point">
                <h3>Save Time and Money</h3>
                No more wasting time dealing with stacks of paper leads. 
                Let us save you the stress and money by cutting out paper, 
                completely, and entering leads in our user friendly environment.
            </div>
        </div>
        <div class="span4 index-content-point">
            <div class="index-content-point">
                <h3>Easily Access Your Leads</h3>
                Access your leads virtually anywhere with our web based Lead 
                Management Software. As long as you have an internet connection, 
                you are able to pull up any lead on your mobile, tablet, or desktop device.
            </div>
        </div>
    </div>
    <div class="row" id="index-content-row">
        <div class="span4">
            <div class="index-content-point">
                <h3>Perfect For Businesses of Every Size</h3>
                From the small, one man operation, to the large contracting firm, 
                our Lead Management Software easily integrates into your current workflow.                
            </div>
        </div>
        <div class="span4 index-content-point">
            <div class="index-content-point">
                <h3>Easy On Your Pockets</h3>
                By giving you the option to easily pick and choose which features 
                you want enabled, you will be saving money on features that go unused.
            </div>
        </div>
        <div class="span4 index-content-point">
            <div class="index-content-point">
                <h3>And More…</h3>
                Our goal is to let our Lead Management Software cater to your business. 
                As we expand our product, we would like to know what features your 
                business is looking for. Let us know here.
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span10 offset1" id="email-form">
            <div class="row">
                <div class="span10" id="email-form-header">
                    Sign up now and lock in your price for $25/month
                </div>
            </div>
            <div class="row">
                <form method="post" action="/thanks">
                    <div class="span6" id="email-form-form">
                        <p><input type="text" class="input-xlarge" id="email-form-input" placeholder="Email Address"/></p>
                        <p><input type="submit" class="btn btn-warning btn-large" id="email-form-button" value="LOCK IN MY PRICE"/>
                    </div>
                    <div class="span4" id="email-form-summary">
                        We are currently working hard to get this amazing product to you.
                        Give us your email to stay updated on the launch date.
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span12 index-content-main">
            <h2 style="margin-top: 45px;margin-bottom: 45px;">The always online<br />solution that's light<br /> on your pocket!</h2>
        </div>
    </div>
</div>