
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>The Best Price</h1>
    <p class="lead">For the carport, garage, or building you need.</p>
    <p><a class="btn btn-lg btn-success" href="/get-started" role="button">Get started today</a></p>
</div>


<div class="row">
    <div class="col-lg-4">
        <div style="text-align: center;"><img src="/img/aframe.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:300px;" /></div>
        <h2 style="text-align: center;">Carports</h2>
        <p>We offer a wide range of carports and carport styles including portable carports, metal carports, carport kits and steel carports. Need a carport built to suit? 100% American made and supplied carports all come with a 10 year rust-through warranty. Countless options available, give us a call today and get started.</p>
        <p><a class="btn btn-primary" href="/carports" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
        <div style="text-align: center;"><img src="/img/shop.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:300px;height:194px;" /></div>
        <h2 style="text-align: center;" >Garages</h2>
        <p>We also specialize in enclosed buildings and shop style garages, built to last. All TurtleBuilt structures come with a 10 year rust-through warranty. Have a special need? Contact us today to get an estimate. </p>
        <p><a class="btn btn-primary" href="/garages" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
        <div style="text-align: center;"><img src="/img/building.jpg" style="-webkit-border-radius: 6px;-moz-border-radius:6px;border-radius:6px;width:300px;height:194px;" /></div>
        <h2 style="text-align: center;">Buildings</h2>
        <p>Agricultural buildings, garden sheds, cottages, farm houses, dog sheds, chicken coops - we do it all. Need a specialized building? Call for an estimate today!</p>
        <p><a class="btn btn-primary" href="/buildings" role="button">View details &raquo;</a></p>
    </div>
</div>